ALTER TABLE IF EXISTS public."Profili"
  ADD COLUMN IF NOT EXISTS paese text,
  ADD COLUMN IF NOT EXISTS genere text,
  ADD COLUMN IF NOT EXISTS distillato_preferito text,
  ADD COLUMN IF NOT EXISTS cocktail_preferito text,
  ADD COLUMN IF NOT EXISTS intensita_preferita text,
  ADD COLUMN IF NOT EXISTS profilo_gustativo_preferito text,
  ADD COLUMN IF NOT EXISTS famiglia_aromatica_preferita text,
  ADD COLUMN IF NOT EXISTS metodo_consumo_preferito text,
  ADD COLUMN IF NOT EXISTS numero_recensioni integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS numero_locali_visitati integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS numero_cocktail_creati integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS recensioni jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS cocktail_creati jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS locali_segnalati jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS preferiti jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS instagram text,
  ADD COLUMN IF NOT EXISTS tiktok text,
  ADD COLUMN IF NOT EXISTS sito_web text,
  ADD COLUMN IF NOT EXISTS esperienza_anni integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS certificazioni text,
  ADD COLUMN IF NOT EXISTS menu_caricato text,
  ADD COLUMN IF NOT EXISTS indirizzo_locale text,
  ADD COLUMN IF NOT EXISTS citta_locale text,
  ADD COLUMN IF NOT EXISTS partita_iva text,
  ADD COLUMN IF NOT EXISTS numero_dipendenti integer DEFAULT 0,
  ADD COLUMN IF NOT EXISTS descrizione_locale text;