create extension if not exists pgcrypto;

create table if not exists public.vini (
  id uuid primary key default gen_random_uuid(),
  name text,
  annata text,
  cantina text,
  vitigno text,
  grado_alcolico text,
  zona text,
  denominazione text,
  image text,
  limpidezza text,
  colore text,
  consistenza text,
  effervescenza text,
  intensita_olfattiva text,
  complessita text,
  qualita_olfattiva text,
  descrizione_olfattiva text,
  zuccheri text,
  alcoli text,
  polialcoli text,
  acidita text,
  tannini text,
  sali_minerali text,
  equilibrio text,
  intensita_gusto text,
  persistenza text,
  qualita_gusto text,
  corpo text,
  stato_evolutivo text,
  armonia text,
  abbinamenti text,
  temperatura_servizio text,
  note_personali text,
  valutazione integer,
  created_at timestamp default now()
);
