[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/admin-update-article"
  to = "/.netlify/functions/admin-update-article"
  status = 200

[[redirects]]
  from = "/api/admin-save-wine"
  to = "/.netlify/functions/admin-save-wine"
  status = 200

[[redirects]]
  from = "/api/admin-save-cocktail"
  to = "/.netlify/functions/admin-save-cocktail"
  status = 200

[[redirects]]
  from = "/api/admin-save-locale"
  to = "/.netlify/functions/admin-save-locale"
  status = 200

[[redirects]]
  from = "/api/auth-signup-custom"
  to = "/.netlify/functions/auth-signup-custom"
  status = 200

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/manifest.json"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
